# Generated by Django 4.2.3 on 2023-07-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pays', '0003_alter_pays_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pays.pays')),
            ],
        ),
    ]
