# Generated by Django 4.2.3 on 2023-07-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbiteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbiteur',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='orbiteur',
            name='pays',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orbiteur',
            name='poids',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orbiteur',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='orbiteur',
            name='nom',
            field=models.CharField(default='Orbiteur', max_length=200),
        ),
    ]
