# Generated by Django 4.2.3 on 2023-07-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbiteur', '0002_orbiteur_description_orbiteur_pays_orbiteur_poids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbiteur',
            name='pays',
            field=models.CharField(choices=[('US', 'United States'), ('FR', 'France'), ('CN', 'China'), ('RU', 'Russia'), ('IT', 'Italy')], max_length=20),
        ),
    ]
