# Generated by Django 4.2.3 on 2023-07-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbiteur', '0003_alter_orbiteur_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbiteur',
            name='type',
            field=models.CharField(choices=[('Communication', 'Communication'), ('Observation', 'Observation'), ('Métérologie', 'Métérologie'), ('Navigation', 'Navigation'), ('Recherche', 'Recherche')], max_length=200),
        ),
    ]
