# Generated by Django 4.2.3 on 2023-07-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbiteur', '0005_alter_orbiteur_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbiteur',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='orbiteur',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
