# Generated by Django 4.2.3 on 2023-07-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbiteur', '0006_orbiteur_latitude_orbiteur_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='orbiteur',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
