# Generated by Django 4.2.3 on 2023-07-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='mom',
            field=models.CharField(default='sans nom, inconnu ou non renseigné', max_length=100, unique=True),
        ),
    ]
