# Generated by Django 4.2.3 on 2023-07-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name': 'Pays'},
        ),
    ]
