# Generated by Django 4.2.3 on 2023-07-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pays', '0002_alter_pays_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pays',
            options={'verbose_name_plural': 'Pays'},
        ),
    ]
